apiVersion: v1
kind: Service
metadata:
  name: frostyyeti-crowdfund-service
  namespace: frostyyeti-ns
spec:
  selector:
    app: frostyyeti-crowdfund
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer