apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frostyyeti-crowdfund
    namespace: frostyyeti-namespace
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70