apiVersion: apps/v1
kind: Deployment
metadata:
  name: frostyyeti-crowdfund
  labels:
    app: frostyyeti-crowdfund
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frostyyeti-crowdfund
  template:
    metadata:
      labels:
        app: frostyyeti-crowdfund
    spec:
      containers:
        - name: frostyyeti-crowdfund
          namespace: frostyyeti-ns1
          image: gcr.io/frostyyeti/frostyyeti-react:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always