---
- name: Configure GKE Cluster
  hosts: localhost
  gather_facts: no
  vars:
    project_id: "frostyyeti"
    cluster_name: "frostyyeti-gke"
    cluster_zone: "us-central1"
    app_name: "frostyyeti-crowdfund"
    image_name: "gcr.io/frostyyeti/frostyyeti-react:latest"
    namespace: "frostyyeti-namespace"
  tasks:
    - name: Run kubectl command to create namespace
      ansible.builtin.shell:
        cmd: kubectl create namespace frostyyeti-namespace
    - name: Apply deployment
      ansible.builtin.shell:
        cmd: kubectl apply -f react-deployment.yaml
      args:
        chdir: ./kubernetes
    - name: Apply deployment
      ansible.builtin.shell:
        cmd: kubectl apply -f react-service.yaml
      args:
        chdir: ./kubernetes
