- name: Deploy React App to GKE
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  become_method: sudo
  vars:
    project_id: "frostyyeti"
    cluster_name: "frostyyeti-gke"
    cluster_zone: "us-central1"
    app_name: "frostyyeti-crowdfund"
    image_name: "gcr.io/frostyyeti/frostyyeti-react:latest"
  tasks:
    - name: Ensure GKE cluster is running
      command: gcloud container clusters get-credentials {{ cluster_name }} --zone {{ cluster_zone }} --project {{ project_id }}

    - name: Create a k8s namespace  
      k8s:    
        state: present    
        definition:      
          apiVersion: v1      
          kind: Namespace      
          metadata:        
            name: "{{ namespace }}"

    - name: Deploy React App
      k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ app_name }}"
            namespace: "{{ namespace }}"
            labels:
              app: "{{ app_name }}"
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: "{{ app_name }}"
            template:
              metadata:
                labels:
                 app: "{{ app_name }}"
              spec:
                containers:
                - name: "{{ app_name }}"
                  image: "{{ image_name }}"
                  ports:
                  - containerPort: 80
        state: present

    - name: Create a Service to expose the app
      k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ app_name }}-service"
          spec:
            selector:
              app: "{{ app_name }}"
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: LoadBalancer
        state: present
