---
- name: Configure GKE Cluster
  hosts: gke_cluster
  gather_facts: no
  vars:
    project_id: "frostyyeti"
    cluster_name: "frostyyeti-gke"
    cluster_zone: "us-central1"
    app_name: "frostyyeti-crowdfund"
    image_name: "gcr.io/frostyyeti/frostyyeti-react:latest"
    namespace: "frostyyeti-namespace"
  tasks:
    - name: Install kubectl
      become: yes
      apt:
        name: kubectl
        state: present

    - name: Configure kubectl
      become: yes
      shell: gcloud container clusters get-credentials {{ cluster_name }} --zone {{ cluster_zone }} --project {{ project_id }}
