---
- name: Configure GKE Cluster
  hosts: localhost
  gather_facts: no
  vars:
    project_id: "frostyyeti"
    cluster_name: "frostyyeti-gke"
    cluster_zone: "us-central1"
    app_name: "frostyyeti-crowdfund"
    image_name: "gcr.io/frostyyeti/frostyyeti-react:latest"
    namespace: "frostyyeti-namespace"
  tasks:
    - name: Check if namespace exists
      ansible.builtin.shell:
        cmd: kubectl get namespace frostyyeti-ns
      register: namespace_check
      ignore_errors: yes
    - name: Create namespace if it doesn't exist
      ansible.builtin.command:
        cmd: kubectl create namespace frostyyeti-ns
      when: namespace_check.rc != 0
    - name: Apply deployment
      ansible.builtin.shell:
        cmd: kubectl apply -f react-deployment.yaml
      args:
        chdir: ../kubernetes
    - name: Apply Service
      ansible.builtin.shell:
        cmd: kubectl apply -f react-service.yaml
      args:
        chdir: ../kubernetes
    - name: Apply Scaling
      ansible.builtin.shell:
        cmd: kubectl apply -f react-hpa.yaml
      args:
        chdir: ../kubernetes
