name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job and Return Result
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: ${{ secrets.JENKINS_SERVER_URL }} # URL of the Jenkins server
          jenkins-job: "test-job" # The name of the Jenkins job to run
          jenkins-username: ${{ secrets.JENKINS_USER }} # Username for accessing Jenkins
          jenkins-pat: ${{ secrets.JENKINS_PIPELINE_TOKEN }} # Personal Access Token for accessing Jenkins
          poll-time: 10 # How often (seconds) to poll the Jenkins server for results
          timeout-value: 600 # How long (seconds) to poll before timing out the action
          verbose: true # Enable extra logging
