name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  trigger-jenkins-pipeline:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      # - name: Trigger Jenkins Pipeline
      #   run: curl -X POST "http://104.198.220.47/job/test-pipeline/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}" 
      - name: Trigger Jenkins Job and Return Result
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: ${{ secrets.JENKINS_SERVER_URL }} # URL of the Jenkins server
          jenkins-job: "test-pipeline" # The name of the Jenkins job to run
          jenkins-username: ${{ secrets.JENKINS_USER }} # Username for accessing Jenkins
          jenkins-pat: ${{ secrets.JENKINS_PIPELINE_TOKEN }} # Personal Access Token for accessing Jenkins
          poll-time: 10 # How often (seconds) to poll the Jenkins server for results
          timeout-value: 600 # How long (seconds) to poll before timing out the action
          verbose: true # Enable extra logging
      
